### ISSUE TITLE
County demographics/shape info is date independent

### ISSUE THREAD

**Issue by paulavery1951** [ringhilterra/enriched-covid19-data#1]
Thanks for the extra work putting this information together. I just wanted to point out that since the demographics and geography of each county are date independent (during the short timescale of Covid-19 cases) you could make a separate file with just that information and not worry about keeping your files up to date with the NYT data.

I wrote a Python program that extracted the population data into a separate file about 1000x smaller. :-) It's extremely useful information for calculating per capita rates.

**Comment by ringhilterra** [comment]
Good point! I will include both the separated population data and separate county shape file too in the repository. 

The reason I kept everything together in a single file is so that the file is ready and easy to use for analysis. Those with less data manipulation skills (like joining different datasets) wouldn't have to spend the extra time figuring out to join themselves

**Comment by ringhilterra** [comment]
Okay done, I added some additional smaller files, including a file with only the county population and shape data.

**Comment by paulavery1951** [comment]
Hi, thanks for the quick update. I was away doing other work and missed this nice update. I realized soon after I opened this issue that having the extra per capita info available for each date would be very beneficial without having to calculate it yourself. Anyway, nice job. :-)
